version: '3'
services:
  php-teste1:
    image: phpv1
    #    environment:
    #      - MYSQL_ROOT_PASSWORD=restore*2022
    #      - MYSQL_DATABASE=development
    #      - MYSQL_USER=devuser
    #      - MYSQL_PASSWORD=secure
    #      - LANG=C.UTF_8
    #    volumes:
    #- db-volume:/var/lib/mysql
    #- "/var/lib/mysql:/home/dockerfiles/mysql_restore/dados/"
    #       - "restore_20211210:/var/lib/mysql"
    ports:
      - "8081:8081"
        #volumes:
        #  restore_20211210:


#volumes:
#    db-volume: /home/dockerfiles/mysql_restore/dados/
